### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by STK913** [alvistack/docker-fisheye#1]
Hello,

I am trying to install the docker with docker-compose under Rancher, but I have an error with the installation, with or without volume:
```
27/08/2019 10:33:40+ exec /etc/init.d/fisheye start -fg
27/08/2019 10:33:40Starting Fisheye:
27/08/2019 10:33:40OpenJDK 64-Bit Server VM warning: Unable to open cgroup memory limit file /sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)
27/08/2019 10:33:40log4j:WARN No appenders could be found for logger (fisheye).
27/08/2019 10:33:40log4j:WARN Please initialize the log4j system properly.
27/08/2019 10:33:40log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
27/08/2019 10:33:41log4j:ERROR setFile(null,true) call failed.
27/08/2019 10:33:41java.io.FileNotFoundException: /var/atlassian/application-data/fisheye/var/log/atlassian-fisheye-2019-08-27.log (No such file or directory)
27/08/2019 10:33:41	at java.io.FileOutputStream.open0(Native Method)
27/08/2019 10:33:41	at java.io.FileOutputStream.open(FileOutputStream.java:270)
27/08/2019 10:33:41	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
27/08/2019 10:33:41	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
27/08/2019 10:33:41	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
27/08/2019 10:33:41	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
27/08/2019 10:33:41	at com.cenqua.fisheye.logging.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:100)
27/08/2019 10:33:41	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
27/08/2019 10:33:41	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:295)
27/08/2019 10:33:41	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
27/08/2019 10:33:41	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
27/08/2019 10:33:41	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
27/08/2019 10:33:41	at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:492)
27/08/2019 10:33:41	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1001)
27/08/2019 10:33:41	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:867)
27/08/2019 10:33:41	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
27/08/2019 10:33:41	at com.cenqua.fisheye.ctl.BaseCommand.setupLogging(BaseCommand.java:219)
27/08/2019 10:33:41	at com.cenqua.fisheye.ctl.Run.mainImpl(Run.java:64)
27/08/2019 10:33:41	at com.cenqua.fisheye.ctl.Run.main(Run.java:55)
27/08/2019 10:33:41	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
27/08/2019 10:33:41	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
27/08/2019 10:33:41	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
27/08/2019 10:33:41	at java.lang.reflect.Method.invoke(Method.java:498)
27/08/2019 10:33:41	at com.cenqua.fisheye.FishEyeCtl.mainImpl(FishEyeCtl.java:101)
27/08/2019 10:33:41	at com.cenqua.fisheye.FishEyeCtl.main(FishEyeCtl.java:44)
27/08/2019 10:33:412019-08-27 08:33:41,061 INFO  - Using log4j configuration file: /opt/atlassian/fisheye/log4j.xml
27/08/2019 10:33:412019-08-27 08:33:41,067 ERROR - Had problem creating directory /var/atlassian/application-data/fisheye/var
27/08/2019 10:33:412019-08-27 08:33:41,067 ERROR - Could not open /var/atlassian/application-data/fisheye/var/fisheye.lck : /var/atlassian/application-data/fisheye/var/fisheye.lck (No such file or directory)
27/08/2019 10:33:412019-08-27 08:33:41,074 ERROR - Another instance of Fisheye and Crucible seems to be running
27/08/2019 10:33:41done.
```

The files are never persisted, it looks like the error occurs while initializing the Docker.

Here is the docker-compose:
```
version: '2'
services:

  fisheye:
    image: alvistack/fisheye:4.7
    ports:
      - 8083:8060
    volumes:
      - /docker/fisheye:/var/atlassian/application-data/fisheye:rw
```

Do you have an idea ?

**Comment by hswong3i** [comment]
See here:
```
27/08/2019 10:33:412019-08-27 08:33:41,067 ERROR - Had problem creating directory /var/atlassian/application-data/fisheye/var
27/08/2019 10:33:412019-08-27 08:33:41,067 ERROR - Could not open /var/atlassian/application-data/fisheye/var/fisheye.lck : /var/atlassian/application-data/fisheye/var/fisheye.lck (No such file or directory)
27/08/2019 10:33:412019-08-27 08:33:41,074 ERROR - Another instance of Fisheye and Crucible seems to be running
```

This usually means your mounted folder without correct ownership or permission, check if it belongs to uid 999
